<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DesignationsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('designations')->insert([
            ['id' => 1, 'designation' => 'Deputy Commissioner ICT'],
            ['id' => 2, 'designation' => 'Addl. Deputy Commissioner (G)'],
            ['id' => 3, 'designation' => 'Addl. Deputy Commissioner (R)'],
            ['id' => 4, 'designation' => 'Caretaker'],
            ['id' => 5, 'designation' => 'Incharge CFC'],
            ['id' => 6, 'designation' => 'Incharge Arms'],
            ['id' => 7, 'designation' => 'Arms Clerk'],
            ['id' => 8, 'designation' => 'Computer Operator'],
            ['id' => 9, 'designation' => 'IDP Clerk'],
            ['id' => 10, 'designation' => 'Death/Birth Certificate Operator'],
            ['id' => 11, 'designation' => 'Dispatch Rider'],
            ['id' => 12, 'designation' => 'Scanning Operator'],
            ['id' => 13, 'designation' => 'Incharge MRC'],
            ['id' => 14, 'designation' => 'PA to ADCG'],
            ['id' => 15, 'designation' => 'Domicile Clerk'],
            ['id' => 16, 'designation' => 'Driver with ADC(E)'],
            ['id' => 17, 'designation' => 'Driver'],
            ['id' => 18, 'designation' => 'Domicile Operator'],
            ['id' => 19, 'designation' => 'Protocol Officer/ District Nazar'],
            ['id' => 20, 'designation' => 'Office Boy'],
            ['id' => 21, 'designation' => 'Magistrate'],
            ['id' => 22, 'designation' => 'Assistant Commissioner City'],
            ['id' => 23, 'designation' => 'Assistant Commissioner Nilore'],
            ['id' => 24, 'designation' => 'Naib Tehsildar'],
            ['id' => 25, 'designation' => 'Addl Deputy Commissioner'],
            ['id' => 26, 'designation' => 'Addl Deputy Commissioner (R)'],
            ['id' => 27, 'designation' => 'Addl. Deputy Commissioner HQ'],
            ['id' => 28, 'designation' => 'Naib Qasid'],
            ['id' => 29, 'designation' => 'Addl Deputy Commissioner G'],
            ['id' => 30, 'designation' => 'Assistant Commissioner Rural'],
            ['id' => 31, 'designation' => 'Assistant Commissioner Secct.'],
            ['id' => 32, 'designation' => 'Assist. Commissioner Shalimar'],
            ['id' => 33, 'designation' => 'Assistant Commissioner I/A'],
            ['id' => 34, 'designation' => 'Assistant Commissioner Saddar'],
            ['id' => 35, 'designation' => 'Tehsildar'],
            ['id' => 36, 'designation' => 'HVC to DC, ICT'],
            ['id' => 37, 'designation' => 'PA/UDC (BS-13) to DC, ICT'],
            ['id' => 38, 'designation' => 'Reader to District Magistrate'],
            ['id' => 39, 'designation' => 'PA to AC (Saddar)'],
            ['id' => 40, 'designation' => 'Assistant commissioner'],
            ['id' => 41, 'designation' => 'LDC'],
            ['id' => 42, 'designation' => 'Assistant'],
            ['id' => 43, 'designation' => 'UDC'],
            ['id' => 44, 'designation' => 'Superintendent'],
            ['id' => 45, 'designation' => 'basta Baidar'],
            ['id' => 46, 'designation' => 'Stenotypist'],
            ['id' => 47, 'designation' => 'LDC (BPS-11)'],
            ['id' => 48, 'designation' => 'Girdawar'],
            ['id' => 49, 'designation' => 'Supervisor'],
            ['id' => 50, 'designation' => 'Private Secretary (BS-17)'],
            ['id' => 51, 'designation' => 'Naib Qasid '],
            ['id' => 52, 'designation' => 'Patwari'],
            ['id' => 53, 'designation' => 'AD-Civil Defence'],
            ['id' => 54, 'designation' => 'PA to AC'],
            ['id' => 55, 'designation' => 'Assistant (ADMIN)'],
            ['id' => 56, 'designation' => 'Magistrate 1st Class'],
            ['id' => 57, 'designation' => 'LDC (BS-11)'],
            ['id' => 58, 'designation' => 'Skilled Worker'],
            ['id' => 59, 'designation' => 'Dispach Rider'],
            ['id' => 60, 'designation' => 'Baildar/Fisherman'],
            ['id' => 61, 'designation' => 'Tube Well Machinic'],
            ['id' => 62, 'designation' => 'Fisheries Watcher'],
            ['id' => 63, 'designation' => 'Lab Attendant'],
            ['id' => 64, 'designation' => 'Sweeper'],
            ['id' => 65, 'designation' => 'Fisheries Supervisor'],
            ['id' => 66, 'designation' => 'Lab Assistant'],
            ['id' => 67, 'designation' => 'Chowkidar'],
            ['id' => 68, 'designation' => 'Focal Person of ADC(G)'],
            ['id' => 69, 'designation' => 'Baildar / Fisherman'],
            ['id' => 70, 'designation' => 'PA to ADC(G)'],
            ['id' => 71, 'designation' => 'Deputy Director/Magistrate ICT'],
            ['id' => 72, 'designation' => 'Deputy Head Clerk'],
            ['id' => 73, 'designation' => 'UDC (BPS - 13)'],
            ['id' => 74, 'designation' => 'PA to ADC'],
            ['id' => 75, 'designation' => 'Reader to AC Potohar'],
            ['id' => 76, 'designation' => 'Community Development Officer'],
            ['id' => 77, 'designation' => 'Registry Clerk'],
            ['id' => 78, 'designation' => 'Magistrate First Class'],
            ['id' => 79, 'designation' => 'Photographer'],
            ['id' => 80, 'designation' => 'RDM/Magistrate'],
            ['id' => 81, 'designation' => 'ULDC'],
            ['id' => 82, 'designation' => 'Assistant ADC (E)'],
            ['id' => 83, 'designation' => 'Private Secretary'],
            ['id' => 84, 'designation' => 'PS to Deputy Commissioner ICT'],
            ['id' => 85, 'designation' => 'Arms Operator'],
            ['id' => 86, 'designation' => 'Addl Deputy Commissioner (G)'],
            ['id' => 87, 'designation' => 'Driver to Incharge CFC'],
            ['id' => 88, 'designation' => 'Inspector'],
            ['id' => 89, 'designation' => 'P.A to AC Nilore'],
            ['id' => 90, 'designation' => 'P.A to ADC(East)'],
            ['id' => 91, 'designation' => 'Photocopy Operator'],
            ['id' => 92, 'designation' => 'Driver to ADCG'],
            ['id' => 93, 'designation' => 'Assistant Director LG & RD'],
            ['id' => 94, 'designation' => 'LDC (BSP-11)'],
            ['id' => 95, 'designation' => 'Magistrage 1st Class'],
            ['id' => 96, 'designation' => 'Assistant  Commissioner Saddar'],
            ['id' => 97, 'designation' => 'Assistant Commissioner (Rural)'],
            ['id' => 98, 'designation' => 'Sanitary Worker'],
            ['id' => 99, 'designation' => 'Mali'],
            ['id' => 100, 'designation' => 'Assistant Commissioner Potohar'],
            ['id' => 101, 'designation' => 'DR'],
        ]);
    }
}
